### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by arpitjindal97** [xgfone/go-opentelemetry#1]
```
# github.com/xgfone/go-opentelemetry
../../go/pkg/mod/github.com/xgfone/go-opentelemetry@v0.3.0/resource.go:39:23: undefined: HTTPClient
```

**Comment by xgfone** [comment]
I have moved the functions about `http` into the sub-package `otelhttpx`, but forgot the http initialization.

It has been **fixed**. Please use `github.com/xgfone/go-opentelemetry@v0.3.1` and `github.com/xgfone/go-opentelemetry/otelhttpx@v0.3.1`. See [Example](https://github.com/xgfone/go-opentelemetry#example).

**Comment by arpitjindal97** [comment]
Thanks for the fix!

One thing which kept me thinking is `operation`. This kind of defines the task that an HTTP handler tends to do in a particular API call.

But looking at the implementation otel has done. It means `server_name`. In the final metrics, it's displayed as `http_server_name`

<img width="670" alt="image" src="https://user-images.githubusercontent.com/15676216/183736049-329bd634-e9ee-418e-9ec4-84dfd61be712.png">

Let me know what are your thoughts on this. What could be a better way to collect metrics for each endpoint ?

Reference:

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/handler_example_test.go#L98-L101

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/handler.go#L207-L212

https://github.com/open-telemetry/opentelemetry-go/blob/main/semconv/internal/http.go#L209-L219

**Comment by xgfone** [comment]
Yes.

It should be an `operation`, such as `Action` or `Method+URL path`, used by `metric` and `tracing`, but `OpenTelemetry` **SHOULD NOT** use the operation as the http server name, that's, passing it to `HTTPServerAttributesFromHTTPRequest` and `HTTPServerMetricAttributesFromHTTPRequest`.

**Comment by arpitjindal97** [comment]
I have opened an [issue](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2645) on them. Would be helpful if you could also subscribe to it for notifications 😁

**Comment by arpitjindal97** [comment]
Found a way to achieve it

Inside Handle func
```
labeler, _ := otelhttp.LabelerFromContext(r.Context())
labeler.Add(semconv.HTTPRouteKey.String(route))
```

Pass empty string as operation
